name: HTMLHint (HTML)

on: [ push ]

jobs:
  stylelint:
    name: Run htmlhint scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install HTMLHint
        run: npm install htmlhint

      - name: Run HTMLHint
        run: npx htmlhint "**/*.html"