name: StyleLint (CSS)

on: [ push ]

jobs:
  stylelint:
    name: Run stylelint scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install StyleLint
        run: npm install stylelint

      - name: Run StyleLint
        run: npx stylelint "**/*.{css,scss}"